#!/bin/bash

psql << EOF
CREATE DATABASE $POSTGRES_DATABASE ENCODING 'UTF8';
CREATE USER $POSTGRES_USER WITH PASSWORD $POSTGRES_PASSWORD;
GRANT ALL PRIVILEGES ON DATABASE  $POSTGRES_DATABASE TO $POSTGRES_USER;
\c $POSTGRES_DATABASE
CREATE SCHEMA IF NOT EXISTS $POSTGRES_SCHEMA;
EOF
