module.exports = {

    help: `This bot can retrieve your Xbox Live gamerscore and use it to generate leaderboards for your group chats.
The base command list can be viewed by using the command /list.\n
The Xbox Live gamerscores are being updated overnight.
In case the Xbox Live gamerscore has failed to update for a specific user more than 2 time, the system removes problematic gamertag from associated telegram user.
If the affected user is present in any of the group chats that has service notification settings enabled, they will recieve a notification about gamertag removal.
This is only working if affected user is present in any of eligible group chats. The bot is not sending any notifications in the DMs.`,

    howTo: `<b>For group chat admins:</b>
It's recommended to use the /config comand and configure a bot for your group chat.
This is not mandatory, but allows you to control some of bot's functions.\n
<b>For regular users:</b>
1. You need to register in the bot using the following command: /register.\n
2. Then you have to set your Xbox Live gamertag.
For that you need to use the following command: /gamertag_set.\n
Here's a usage example for a normal gamertag - <code>GeraltFromRivia</code>:
<code>/gamertag_set GeraltFromRivia</code>\n
Here's a usage example for a gamertag with unique number - <code>GeraltFromRivia#1524</code>:
<code>/gamertag_set GeraltFromRivia1524</code>\n
3. Next, you need to wait for an automatic daily update or initiate a manual update /live_upd.\n
In case of success, the bot will inform you. In case of any errors, the bot will specify the error reason.\n
From now on you'll be included in the group chat leaderboards, which can be generated by using the command /live_lb.\n
Every first day of the months bot takes a snapshot of your current gamerscore. This allows the bot to track monthly gamerscore and create a monthly leaderboard for the group chat, command /monthly_lb.
In case you don't have a monthly snapshot set up already, use the command /monthly_score. This will take a snapshot for a month and will start counting the monthly score,
should you already have the monthly snapshot taken, the command will show your monthly score. If your gamerscore equals zero it won't be included in the leaderboard.`,

    cmdList: `/help - General information about the bot.
/how_to - How to use the bot.
/register - Registers you in the database.
/update - Updates information about your telegram profile.
/privacy - Shows what personal information is used by a bot.
/xbox_list - Shows the list of command related to Xbox Live.
/ping - just a ping, replies with 'pong'.
/config - Create/edit group chat settings for bot. Available only to the group chat admins.`,

    xboxCmdList: `/gamertag_set - Attaches your Xbox Live gamertag to your Telegram account. Requires registration.
/live_upd - Allows to update your gamerscore manually, available one time per day.
/live_lb - Generates an Xbox Live leaderboard by the all-time gamerscore for the group chat.
/live_score - Shows Xbox Live gamertag and gamerscore for you or user from reply.
/monthly_lb - Generates an Xbox Live leaderboard by the monthly gamerscore for the group chat.
/monthly_score - Forces to create a monthly snapshot if not created already. Otherwise shows the current known monthly score.`,

    xbotGameCmdList: `/xbot_join - Registers you in the mini-game.
/xbot_me - Shows your mini-game stats and participation status.
/xbot_stat - Shows the mini-game leaderboard for the current year in the current group chat (minimum 3 participants).
/xbot_all - Shows the all-time mini-game leaderboard in the current group chat (minimum 3 participants).
/xbot_pause - Changes your mini-game participation status (Paused/Unpaused) for the current group chat.
/xbot - Launches the mini-game.`,

    privacy: `Prior to the use of a /register command bot doesn't collect any data from you as a Telegram user.

After the registration bot stores your Telegram User ID, username (if present), and your first name in the database.
If bot's access to your user profile haven't been revoked it attempts to update information about your first name and username on a daily basis.

For participation in the Xbot mini-game bot also stores the Group Chat ID that you are the member of. There might be multiple Group Chat ID records.

To retrive your Xbox Live related information this bot uses his own Xbox Live scraper account, this account automatically collects publically available Xbox Live information about your profile.
This means that you don't need to provide any private information like passwords or emails for bot to operate. But when you provide your gamertag to bot it's also being stored in the database.

Group Chats: if the /config command has been used or someone has registered in the Xbot mini-game, the Group Chat ID is being stored in the database.

If bot still has the access to the user telegram profile, it may get publically visible telegram profile information on a regular basis.
Telegram users can revoke bot's access to their profiles by blocking the bot in DMs, but the Telegram server also revokes the access after some time has passed after the last time user has interacted with a bot directly.`

}
